- name: Find and setup MLAG peer
  delegate_to: localhost
  block:
  - name: bla
    community.routeros.api_facts:
      hostname: "{{ ansible_host }}"
      password: "{{ password }}"
      username: "{{ username }}"
      gather_subset:
      - "interfaces"
  - name: output
    debug:
      msg: "{{ansible_net_neighbors }}"

#  - name: Discover MLAG interfaces using LLDP
#    community.routeros.api:
#      hostname: "{{ item.hostname }}"
#      password: "{{ password }}"
#      username: "{{ username }}"
#      path: "ip neighbor"
#      query: "interface WHERE system-name == {{ routers | map(attribute='name') | list }}"
#    register: lldp_neighbors
#    loop: "{{ routers }}"
#  
#- name: Enable MLAG dynamically on discovered interfaces
#  community.routeros.api:
#    hostname: "{{ item.hostname }}"
#    password: "{{ password }}"
#    username: "{{ username }}"
#    path: "interface bonding"
#    add: "mode=802.3ad lacp-rate=fast interfaces={{ lldp_neighbors[item.hostname] | map(attribute='interface') | join(',') }}"
#  loop: "{{ routers }}"
#
