- name: Setup basic Router
  hosts: mikrotik_switches
  become: false
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      password: "{{ password }}"
      username: "{{ username }}"
      tls: false
      validate_certs: false
      validate_cert_hostname: false
  tasks:
    - name: Include VLAN role
      include_role:
        name: mdombek.mikrotik.vlans
      loop: "{{ vlans | dict2items }}"
      loop_control:
        loop_var: vlan
        label: "{{ vlan.key }}"
      #tags: vlans



#    roles:
  #- role: mdombek.mikrotik.base_setup
#    tags: base_setup

#
#  - role: mdombek.mikrotik.vrrp
#    tags: vrrp
#  - role: mdombek.mikrotik.lacp
#    tags: lacp
#    loop: "{{ lacp_ports }}"
#  - role: mdombek.mikrotik.port_config
