---
- name: Configure LACP interfaces based on LLDP neighbors
  delegate_to: localhost
  module_defaults:
    community.routeros.api:
      hostname: "{{ ansible_host }}"
      password: "{{ password }}"
      username: "{{ username }}"
    community.routeros.api_modify:
      hostname: "{{ ansible_host }}"
      password: "{{ password }}"
      username: "{{ username }}"
  block:
    - name: Gather LLDP neighbor information
      community.routeros.api:
        path: "ip neighbor"
        cmd: "print"
      register: lldp_neighbors

    - name: Get all PVE node hostnames
      ansible.builtin.set_fact:
        pve_hostnames: "{{ groups['pve_nodes'] | map('regex_replace', '^(.*)', '\\1') | list }}"
        _ignored_ifs: "{{ ignore_system_interfaces | default([]) + ignore_interfaces | default([]) }}"

    - name: debug  show pve hostnames
      ansible.builtin.debug:
        msg: "{{ pve_hostnames }}"

    - name: Create clean interface list
      ansible.builtin.set_fact:
        _clean_interfaces: "{{ _clean_interfaces | 
            default([]) + [{'host': item.identity, 
            'interfaces': item.interface | split(',') | difference(_ignored_ifs) }] }}"
      loop: "{{ lldp_neighbors.msg }}"

    - name: Configure LACP interfaces
      community.routeros.api_modify:
        path: "interface bonding"
        data:
          - name: "{{ lacp_interface_name_template | replace('{host}', item.host) }}"
            mode: "{{ lacp_mode }}"
            slaves: "{{ item.interfaces | join(',') }}"
            lacp-rate: "{{ lacp_rate }}"
            transmit-hash-policy: "{{ transmit_hash_policy }}"
            min-links: "{{ min_links }}"
            comment: "{{ item.host.split('.')[0]}}"
      loop: "{{ _clean_interfaces }}"
      when:
      - item.interfaces | length > 1
      - item.host.split('.')[0] in pve_hostnames or item.host in pve_hostnames
      loop_control:
        label: "Configuring LACP for {{ item.host }} with interfaces {{ item.interfaces | join(',') }}"