---
- name: "Group physical interfaces by assigned server"
  set_fact:
    lacp_groups: >-
      {{
        lacp_groups | default({}) | combine(
          { item.value.connects: (lacp_groups[item.value.connects] | default([])) + [ item.key ] }
        )
      }}
  loop: "{{ ports | dict2items }}"
  when: ports is defined

- name: "Configure LACP for each server group"
  delegate_to: "{{ ansible_controller }}"
  block:
    - name: "Create LACP group for {{ item.key }}"
      include_tasks: _lacp_ports.yaml
      loop: "{{ lacp_groups | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
